from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping

from beam_design.core.actions import ActionSet


class ACIActionSource(Enum):
    DEAD = "D"
    LIVE = "L"
    ROOF_LIVE = "Lr"
    SNOW = "S"
    RAIN = "R"
    WIND = "W"
    EARTHQUAKE = "E"


@dataclass(frozen=True)
class ActionEffect:
    """A scalar action effect generated by analysis for one load source.

    This is intentionally not a raw load object. The value may be a moment,
    shear, axial force, torsion, reaction, line-load action, or another scalar
    effect that has already been produced for a specific load pattern.
    """

    source: ACIActionSource
    value: float
    label: str = ""

    def __post_init__(self) -> None:
        if isinstance(self.source, str):
            object.__setattr__(self, "source", coerce_action_source(self.source))


@dataclass(frozen=True)
class ActionPattern:
    """Action effects at one design section/location for one response type."""

    effects: tuple[ActionEffect, ...] = ()
    label: str = "service actions"

    @classmethod
    def from_values(cls, label: str = "service actions", **values: float) -> "ActionPattern":
        return cls(
            effects=tuple(
                ActionEffect(source=coerce_action_source(key), value=value)
                for key, value in values.items()
            ),
            label=label,
        )

    @classmethod
    def from_action_set(cls, actions: ActionSet) -> "ActionPattern":
        return cls.from_values(label=actions.label, **actions.by_source())

    def total_by_source(self) -> dict[ACIActionSource, float]:
        totals: dict[ACIActionSource, float] = {source: 0.0 for source in ACIActionSource}
        for effect in self.effects:
            totals[effect.source] += effect.value
        return totals


@dataclass(frozen=True)
class ActionCombinationEquation:
    equation: str
    label: str
    factors: Mapping[ACIActionSource, float]
    primary_source: ACIActionSource

    def combine(self, pattern: ActionPattern) -> float:
        totals = pattern.total_by_source()
        return sum(self.factors.get(source, 0.0) * totals[source] for source in ACIActionSource)


@dataclass(frozen=True)
class ActionCombinationResult:
    equation: str
    label: str
    primary_source: ACIActionSource
    value: float
    components: dict[str, float] = field(default_factory=dict)


@dataclass(frozen=True)
class ActionEnvelope:
    results: tuple[ActionCombinationResult, ...]

    @property
    def governing(self) -> ActionCombinationResult:
        if not self.results:
            raise ValueError("Action envelope has no results.")
        return max(self.results, key=lambda result: abs(result.value))

    @property
    def max_positive(self) -> ActionCombinationResult:
        if not self.results:
            raise ValueError("Action envelope has no results.")
        return max(self.results, key=lambda result: result.value)


class ACILoadCombinations:
    """ACI 318-14 Table 5.3.1 action-combination adapter."""

    def equations(self, include_lateral: bool = True) -> tuple[ActionCombinationEquation, ...]:
        equations = (
            ActionCombinationEquation(
                equation="5.3.1a",
                label="1.4D",
                factors={ACIActionSource.DEAD: 1.4},
                primary_source=ACIActionSource.DEAD,
            ),
            ActionCombinationEquation(
                equation="5.3.1b",
                label="1.2D + 1.6L + 0.5(Lr or S or R)",
                factors={
                    ACIActionSource.DEAD: 1.2,
                    ACIActionSource.LIVE: 1.6,
                    ACIActionSource.ROOF_LIVE: 0.5,
                    ACIActionSource.SNOW: 0.5,
                    ACIActionSource.RAIN: 0.5,
                },
                primary_source=ACIActionSource.LIVE,
            ),
            ActionCombinationEquation(
                equation="5.3.1c",
                label="1.2D + 1.6(Lr or S or R) + (1.0L or 0.5W)",
                factors={
                    ACIActionSource.DEAD: 1.2,
                    ACIActionSource.LIVE: 1.0,
                    ACIActionSource.ROOF_LIVE: 1.6,
                    ACIActionSource.SNOW: 1.6,
                    ACIActionSource.RAIN: 1.6,
                    ACIActionSource.WIND: 0.5,
                },
                primary_source=ACIActionSource.ROOF_LIVE,
            ),
            ActionCombinationEquation(
                equation="5.3.1d",
                label="1.2D + 1.0W + 1.0L + 0.5(Lr or S or R)",
                factors={
                    ACIActionSource.DEAD: 1.2,
                    ACIActionSource.WIND: 1.0,
                    ACIActionSource.LIVE: 1.0,
                    ACIActionSource.ROOF_LIVE: 0.5,
                    ACIActionSource.SNOW: 0.5,
                    ACIActionSource.RAIN: 0.5,
                },
                primary_source=ACIActionSource.WIND,
            ),
            ActionCombinationEquation(
                equation="5.3.1e",
                label="1.2D + 1.0E + 1.0L + 0.2S",
                factors={
                    ACIActionSource.DEAD: 1.2,
                    ACIActionSource.EARTHQUAKE: 1.0,
                    ACIActionSource.LIVE: 1.0,
                    ACIActionSource.SNOW: 0.2,
                },
                primary_source=ACIActionSource.EARTHQUAKE,
            ),
            ActionCombinationEquation(
                equation="5.3.1f",
                label="0.9D + 1.0W",
                factors={ACIActionSource.DEAD: 0.9, ACIActionSource.WIND: 1.0},
                primary_source=ACIActionSource.WIND,
            ),
            ActionCombinationEquation(
                equation="5.3.1g",
                label="0.9D + 1.0E",
                factors={ACIActionSource.DEAD: 0.9, ACIActionSource.EARTHQUAKE: 1.0},
                primary_source=ACIActionSource.EARTHQUAKE,
            ),
        )
        if include_lateral:
            return equations
        return tuple(
            equation
            for equation in equations
            if equation.primary_source not in {ACIActionSource.WIND, ACIActionSource.EARTHQUAKE}
        )

    def combine(
        self,
        pattern: ActionPattern,
        include_lateral: bool = True,
    ) -> tuple[ActionCombinationResult, ...]:
        totals = pattern.total_by_source()
        results: list[ActionCombinationResult] = []
        for equation in self.equations(include_lateral=include_lateral):
            value = equation.combine(pattern)
            results.append(
                ActionCombinationResult(
                    equation=equation.equation,
                    label=equation.label,
                    primary_source=equation.primary_source,
                    value=value,
                    components={
                        source.value: factor * totals[source]
                        for source, factor in equation.factors.items()
                        if totals[source] != 0.0
                    },
                )
            )
        return tuple(results)

    def envelope(self, pattern: ActionPattern, include_lateral: bool = True) -> ActionEnvelope:
        return ActionEnvelope(self.combine(pattern, include_lateral=include_lateral))

    def action_envelope(self, pattern: ActionPattern, include_lateral: bool = True) -> ActionEnvelope:
        return self.envelope(pattern, include_lateral=include_lateral)

def coerce_action_source(value: ACIActionSource | str) -> ACIActionSource:
    if isinstance(value, ACIActionSource):
        return value
    normalized = value.strip()
    aliases = {
        "DEAD": ACIActionSource.DEAD,
        "LIVE": ACIActionSource.LIVE,
        "ROOF_LIVE": ACIActionSource.ROOF_LIVE,
        "ROOFLIVE": ACIActionSource.ROOF_LIVE,
        "SNOW": ACIActionSource.SNOW,
        "RAIN": ACIActionSource.RAIN,
        "WIND": ACIActionSource.WIND,
        "EARTHQUAKE": ACIActionSource.EARTHQUAKE,
    }
    upper = normalized.upper()
    if upper in aliases:
        return aliases[upper]
    for source in ACIActionSource:
        if normalized == source.value:
            return source
    raise ValueError(f"{value!r} is not a valid ACI action source.")
